CREATE TABLE ACCOUNT(
  id UUID PRIMARY KEY NOT NULL,
  email varchar(255) DEFAULT NOT NULL UNIQUE,
  accountName varchar(255) DEFAULT NOT NULL UNIQUE,
  balance DECIMAL DEFAULT NULL,
  created TIMESTAMP ,
  lastupdated TIMESTAMP,
  version INTEGER,
  PRIMARY KEY (id)
);
CREATE TABLE TRANSFER(
  id UUID PRIMARY KEY NOT NULL,
  accountFrom UUID DEFAULT NOT NULL,
  accountTo UUID DEFAULT NOT NULL,
  balance DECIMAL DEFAULT NULL,
  created TIMESTAMP,
  version INTEGER,
  PRIMARY KEY (id)
);
